[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "aoc_mojo_day4"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120323,<0.27"
